# Generated by Django 2.1.2 on 2018-10-06 13:42

import annotator.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punchline', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=annotator.models.get_image_path)),
                ('original_img', models.ImageField(blank=True, null=True, upload_to=annotator.models.get_image_path)),
                ('name', models.TextField(default='')),
                ('relevant', models.BooleanField(default=True)),
                ('annotated', models.BooleanField(default=False)),
                ('is_multiple', models.BooleanField(default=False)),
                ('custom_dimensions', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CartoonThemeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FunninessAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funniness', models.IntegerField(blank=True, choices=[(1, '1 ... not funny at all'), (2, '2 ... moderately funny'), (3, '3 ... less than funny'), (4, '4 ... funny'), (5, '5 ... more than funny'), (6, '6 ... hilarious'), (7, '7 ... more than hilarious')], null=True)),
                ('annotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cartoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Cartoon')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnotationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnotationCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotated', models.BooleanField(default=False)),
                ('annotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cartoon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.Cartoon')),
            ],
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='annotation_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.ImageAnnotationClass'),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.ImageAnnotationCollection'),
        ),
    ]
