# Generated by Django 2.0.7 on 2018-07-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_auto_20180714_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
