# Generated by Django 2.1.2 on 2018-11-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_cartoon_duplicate_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='funninessannotation',
            name='i_understand',
            field=models.BooleanField(default=True),
        ),
    ]
