# Generated by Django 2.0.7 on 2018-07-14 14:19

import annotator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_cartoon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='original_img',
            field=models.ImageField(blank=True, null=True, upload_to=annotator.models.get_image_path),
        ),
    ]
