# Generated by Django 2.0.7 on 2018-07-15 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotator', '0004_cartoon_original_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunninessAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funniness', models.IntegerField(blank=True, choices=[(1, '1 ... not funny at all'), (2, '2 ... moderately funny'), (3, '3 ... less than funny'), (4, '4 ... funny'), (5, '5 ... more than funny'), (6, '6 ... hilarious'), (7, '7 ... absolutely hilarious')], null=True)),
                ('annotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
