# Generated by Django 2.0.7 on 2018-07-15 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0005_funninessannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='funninessannotation',
            name='cartoon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotator.Cartoon'),
            preserve_default=False,
        ),
    ]
