# Generated by Django 2.0.7 on 2018-09-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0006_funninessannotation_cartoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='relevant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='funninessannotation',
            name='funniness',
            field=models.IntegerField(blank=True, choices=[(1, '1 ... not funny at all'), (2, '2 ... moderately funny'), (3, '3 ... less than funny'), (4, '4 ... funny'), (5, '5 ... more than funny'), (6, '6 ... hilarious'), (7, '7 ... more than hilarious')], null=True),
        ),
    ]
