# Generated by Django 2.0.7 on 2018-09-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0007_auto_20180927_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='annotated',
            field=models.BooleanField(default=True),
        ),
    ]
