# Generated by Django 2.0.7 on 2018-09-28 17:53

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0009_auto_20180927_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_free_cropping', image_cropping.fields.ImageRatioField('cartoon__img', '1x1', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='min free cropping')),
                ('cartoon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.Cartoon')),
            ],
        ),
    ]
