# Generated by Django 2.0.7 on 2018-10-01 06:35

import annotator.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotator', '0010_imageannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageannotation',
            name='annotated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=annotator.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='imageannotation',
            name='min_free_cropping',
            field=image_cropping.fields.ImageRatioField('cartoon__img', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='min free cropping'),
        ),
    ]
