# Generated by Django 2.0.7 on 2018-10-01 06:38

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0012_auto_20181001_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageannotation',
            name='img',
        ),
        migrations.AlterField(
            model_name='imageannotation',
            name='min_free_cropping',
            field=image_cropping.fields.ImageRatioField('cartoon__img', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='min free cropping'),
        ),
    ]
