# Generated by Django 2.1.2 on 2018-10-01 20:07

import annotator.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0014_auto_20181001_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageannotation',
            name='crop',
            field=annotator.models.CropModelField(default=''),
        ),
    ]
