# Generated by Django 2.1.2 on 2018-10-02 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotator', '0015_imageannotation_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnotationCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cartoon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.Cartoon')),
            ],
        ),
        migrations.RemoveField(
            model_name='imageannotation',
            name='annotated_by',
        ),
        migrations.AlterField(
            model_name='imageannotation',
            name='cartoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.ImageAnnotationCollection'),
        ),
    ]
