# Generated by Django 2.1.2 on 2018-10-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0017_auto_20181002_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageannotationcollection',
            name='annotated',
            field=models.BooleanField(default=False),
        ),
    ]
