# Generated by Django 2.1.2 on 2018-10-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0018_imageannotationcollection_annotated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageannotation',
            name='dimensions',
            field=models.CharField(default='', max_length=100),
        ),
    ]
