# Generated by Django 2.1.2 on 2018-10-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0019_auto_20181002_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnotationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='annotation_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.ImageAnnotationClass'),
        ),
    ]
