# Generated by Django 2.1.2 on 2018-10-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0020_auto_20181002_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='custom_dimensions',
            field=models.CharField(default='', max_length=100),
        ),
    ]
