# Generated by Django 2.1.2 on 2018-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0021_cartoon_custom_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='custom_dimensions',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
