# Generated by Django 2.1.2 on 2018-10-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0022_auto_20181002_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartoonThemeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cartoon',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, to='annotator.CartoonThemeClass'),
        ),
    ]
