# Generated by Django 2.1.2 on 2018-10-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0023_auto_20181003_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='punchline',
            field=models.TextField(blank=True),
        ),
    ]
