# Generated by Django 2.1.2 on 2018-10-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0024_auto_20181005_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoon',
            name='themes',
        ),
    ]
