# Generated by Django 2.1.2 on 2018-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0025_remove_cartoon_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='is_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
